# Generated by Django 5.1.5 on 2025-03-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='fan'),
        ),
    ]
