# Generated by Django 5.1.5 on 2025-03-31 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_match_players_remove_user_role_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
