# Generated by Django 5.0.4 on 2025-04-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_rename_user_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(blank=True),
        ),
    ]
